// Voice validation for WOW SOLUTIONS brand (Greg Baranchuk personal LinkedIn).
// Pulls config from prod DB, generates post, scores via Pangram.
// Run: bun --env-file=.env.local scripts/voice-test-greg-linkedin.ts [topic-key]
// Cost: ~$0.02 (Sonnet + 1 Pangram check).

import { createClient } from "@supabase/supabase-js";
import { generatePost } from "../lib/claude";
import { checkText, deriveDetectionScore } from "../lib/pangram";
import type { Tables } from "../lib/supabase/database.types";

const BRAND_ID = "a828eb58-584b-4a81-b589-157dda2b5204"; // WOW SOLUTIONS

const TOPICS: Record<string, string> = {
  fail: "Why most AI projects inside service businesses fail — and the one filter I use to spot which ones will work",
  xiaomi: "How I redesigned the Xiaomi service network in 2022: closed regional branches, partnered with Xiaomi retail as drop-off points, centralized logistics into one hub. The business went from launch losses to consistent dividends.",
  pipeline: "The $0.18-per-article content engine that broke our SEO ceiling: from 2 articles/month with ChatGPT-assist to 15/month on autopilot, 8× site impressions in month one",
  questions: "The two questions I ask owners before any AI consulting engagement — and why most AI advisors skip both",
  "fail-dogfood": "Why most AI projects inside service businesses fail — and how I came to build my own. The personal angle: for years I never found time to write articles and promote my own business. That pain is exactly what I'm now solving with Sepio, a SaaS that generates and ships LinkedIn posts in my voice. I'm the first user — this exact post was generated by my own product. The filter I now apply: does this AI replace a step a human is doing manually today, in a workflow that already runs? If yes, build it. If not, kill it.",
};

const topicKey = process.argv[2] ?? "fail";
const topic = TOPICS[topicKey];
if (!topic) {
  console.error(`Unknown topic key: ${topicKey}. Available: ${Object.keys(TOPICS).join(", ")}`);
  process.exit(1);
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("Missing SUPABASE env vars");
  process.exit(1);
}

const supabase = createClient(url, key);
const { data: config, error } = await supabase
  .from("brand_configs")
  .select("*")
  .eq("brand_id", BRAND_ID)
  .maybeSingle();

if (error || !config) {
  console.error("Failed to fetch brand_config:", error?.message ?? "not found");
  process.exit(1);
}

console.log(`=== TOPIC (${topicKey}) ===`);
console.log(topic);
console.log("\n=== BRAND CONFIG SUMMARY ===");
console.log(`brand_voice:     ${config.brand_voice?.slice(0, 120)}...`);
console.log(`tone_attrs:      ${config.tone_attributes?.join(", ")}`);
console.log(`forbidden:       ${config.forbidden_words?.length ?? 0} words`);
console.log(`voice_samples:   ${(config.voice_samples as unknown[])?.length ?? 0}`);
console.log(`style_guide:     ${config.style_guide ? "present" : "missing"}`);

const t0 = Date.now();
const draft = await generatePost(config as Tables<"brand_configs">, "en", topic);
const claudeMs = Date.now() - t0;

const p0 = Date.now();
const pangram = await checkText(draft.text);
const pangramMs = Date.now() - p0;

console.log("\n=== DRAFT ===");
console.log(draft.text);
console.log("\n=== PANGRAM ===");
console.log(`prediction:      ${pangram.prediction_short}`);
console.log(`fraction_human:  ${pangram.fraction_human.toFixed(3)}`);
console.log(`fraction_ai:     ${pangram.fraction_ai.toFixed(3)}`);
console.log(`human segments:  ${pangram.num_human_segments}`);
console.log(`AI segments:     ${pangram.num_ai_segments}`);
console.log(`derived score:   ${deriveDetectionScore(pangram)}/100`);
console.log("\n=== USAGE ===");
console.log(`length:          ${draft.text.length} chars`);
console.log(`claude time:     ${claudeMs}ms`);
console.log(`pangram time:    ${pangramMs}ms`);
console.log(`input tokens:    ${draft.usage.input_tokens}`);
console.log(`output tokens:   ${draft.usage.output_tokens}`);
console.log(`cache create:    ${draft.usage.cache_creation_input_tokens}`);
console.log(`cache read:      ${draft.usage.cache_read_input_tokens}`);
